Traceback (most recent call last):
  File "test_vaes.py", line 43, in <module>
    plot_good_and_bad_samples(abnormal_loader, model, device, 20, output_dir +"_abnormal", plot_dir)
  File "/prodi/bioinfdata/user/bioinf3/VAE/src/test.py", line 24, in plot_good_and_bad_samples
    reconstruction_loss, kld_loss = no_reduction_loss_function(x, x_hat, mean, log_var)
  File "/prodi/bioinfdata/user/bioinf3/VAE/src/loss.py", line 15, in no_reduction_loss_function
    reproduction_loss = F.l1_loss(x_hat, x, reduction='none').mean(dim=1)
  File "/prodi/bioinfdata/user/bioinf3/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/functional.py", line 3264, in l1_loss
    return torch._C._nn.l1_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 132.00 MiB (GPU 1; 10.92 GiB total capacity; 8.47 GiB already allocated; 72.69 MiB free; 10.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
